### ISSUE TITLE
No error indication if connection to grampsweb could not be established

### ISSUE THREAD

**Issue by ondrno** [DavidMStraub/gramps-addon-webapisync#10]
Environment: grampsweb 0.17, websync plugin (as of 08.12.2022)

Url is given as https but grampsweb runs at http

Steps to reproduce:
1) grampsweb runs on http://localhost:5000
2) specify url as https://localhost:5000 at login screen
3) continue
4) found exception=<urlopen error [Errno 111] occurs, UI is forwarded to "Summary" page without any indication for the user what was wrong (**NOK**)

**Comment by DavidMStraub** [comment]
I don't understand your point 3 and 4. Can you please provide (much) more details.

If the connection between frontend and backend can't be established, there _is_ an error message.

**Comment by DavidMStraub** [comment]
Sorry, deleted my previous message as I confused repositories.

**Comment by DavidMStraub** [comment]
Fixed by #13 :+1:
