### ISSUE TITLE
Issues with time-based diff

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/gramps-addon-webapisync#5]
Currently the addon determines the "latest identical object" and treats all changes with later timestamp as local, remote, or simultaneous changes.

I was already aware of the following problem:

- Sync
- Add an object remotely
- Delete the object locally
- Sync - the object will be detected as new.

Now I found an additional problem:

- Sync
- Modify an object remotely
- Sync
- Modify the same object locally
- Sync: the change will be detected as simultaneous change, as the second sync will touch the timestamp and the local change will prevent that timestamp to be used as "latest identical object".

To solve these issues, I now had the idea to have an object in both databases that always correctly identifies the "latest common timestamp" by being modified every time there is a successful sync. For instance, a note with a fixed Gramps ID. The only issue I see is that this note would always show up under "recently changed objects", e.g. in Gramps.js, which is a bit annoying.

The main issue is that Gramps doesn't have a "last changed timestamp" at database level.

**Comment by romjerome** [comment]
Maybe to go further? 

A mixup between last changes on a global set of all handles for primary objects. Something like :
```
sorted(dbstate.db.get_primary_object_handles(), key=self._get{primary_object}Timestamp)
```
 or
```
dbstate.db.get_primary_object_from_handle({primary_object_handle}).change
```
where primary_object is just an handle whatever type of object (Person, Family, Event, etc.)

or existing filter rules and a classical monitor (e.g, every hour during a gramps session), something like :
```
from gramps.gen.filters import GenericFilterFactory, rules
filter = GenericFilterFactory(namespace)()
SOURCE_DATE = Today() - 1 # or whatever
filter.add_rule(rules.{object}.ChangedSince(["%s" % SOURCE_DATE, ""]))
```
where {object} is one of the primary object class/type (namespace)

**and** MRU. i.e, into current gramps desktop application 
```history = uistate.get_history(namespace).mru```

Sorry, I cannot properly code/write/translate it, but this can give an overview of the idea.
A global list of changes where one object/handle can be listed a lot of time. 
So, a custom list for metadata history, merging and synchronisation.

**Comment by DavidMStraub** [comment]
Fixed this now (I think) by storing the last synced timestamp in the local config file.
